# Generated by Django 5.0 on 2024-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateacheve',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
