# Generated by Django 5.0 on 2024-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_dateacheve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
